name: Generate Changelog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate changelog
        run: |
          git fetch --prune --unshallow
          npx auto-changelog -p

      - name: Commit changelog
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add changelog.md
          git commit -m "chore: update changelog"
          git push