name: Update ChangeLog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    if: github.actor != 'github-actions'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com" 
          npm install --save-dev standard-version
          npx standard-version --skip.tag=true --skip.bump=true

      - name: Commit and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add CHANGELOG.md
          git diff --quiet && exit 0  
          git commit -m "chore(release): update changelog [skip ci]"
          git push