name: Update ChangeLog

on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate ChangeLog
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          echo "## Changelog" > CHANGELOG.md
          git log --pretty=format:"* %s (%an)" >> CHANGELOG.md

          git add CHANGELOG.md
          git commit -m "chore(release): update changelog" || echo "No changes to commit"
          git push
